add_test([=[GraphTest.BasicTest]=]  /home/be/CPP/algs_uerj/alg/graph/tests/run-graph-tests [==[--gtest_filter=GraphTest.BasicTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GraphTest.BasicTest]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/graph/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TreeTest.PlantTree]=]  /home/be/CPP/algs_uerj/alg/graph/tests/run-graph-tests [==[--gtest_filter=TreeTest.PlantTree]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TreeTest.PlantTree]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/graph/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SumTests.Sum1]=]  /home/be/CPP/algs_uerj/alg/graph/tests/run-graph-tests [==[--gtest_filter=SumTests.Sum1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SumTests.Sum1]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/graph/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SumTests.Sum2]=]  /home/be/CPP/algs_uerj/alg/graph/tests/run-graph-tests [==[--gtest_filter=SumTests.Sum2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SumTests.Sum2]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/graph/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  run-graph-tests_TESTS GraphTest.BasicTest TreeTest.PlantTree SumTests.Sum1 SumTests.Sum2)
