add_test([=[NoArraySingleLinkTest.InsertAndBasicStructure]=]  /home/be/CPP/algs_uerj/alg/list/tests/run-list-tests [==[--gtest_filter=NoArraySingleLinkTest.InsertAndBasicStructure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoArraySingleLinkTest.InsertAndBasicStructure]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoArraySingleLinkTest.Delete]=]  /home/be/CPP/algs_uerj/alg/list/tests/run-list-tests [==[--gtest_filter=NoArraySingleLinkTest.Delete]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoArraySingleLinkTest.Delete]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoPointerSingleLinkTest.InsertAndBasicStructure]=]  /home/be/CPP/algs_uerj/alg/list/tests/run-list-tests [==[--gtest_filter=NoPointerSingleLinkTest.InsertAndBasicStructure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoPointerSingleLinkTest.InsertAndBasicStructure]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoPointerSingleLinkTest.Delete]=]  /home/be/CPP/algs_uerj/alg/list/tests/run-list-tests [==[--gtest_filter=NoPointerSingleLinkTest.Delete]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoPointerSingleLinkTest.Delete]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoArrayDoubleLinkTest.InsertAndBasicStructure]=]  /home/be/CPP/algs_uerj/alg/list/tests/run-list-tests [==[--gtest_filter=NoArrayDoubleLinkTest.InsertAndBasicStructure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoArrayDoubleLinkTest.InsertAndBasicStructure]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoArrayDoubleLinkTest.Delete]=]  /home/be/CPP/algs_uerj/alg/list/tests/run-list-tests [==[--gtest_filter=NoArrayDoubleLinkTest.Delete]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoArrayDoubleLinkTest.Delete]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoPointerDoubleLinkTest.InsertAndBasicStructure]=]  /home/be/CPP/algs_uerj/alg/list/tests/run-list-tests [==[--gtest_filter=NoPointerDoubleLinkTest.InsertAndBasicStructure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoPointerDoubleLinkTest.InsertAndBasicStructure]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoPointerDoubleLinkTest.Delete]=]  /home/be/CPP/algs_uerj/alg/list/tests/run-list-tests [==[--gtest_filter=NoPointerDoubleLinkTest.Delete]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoPointerDoubleLinkTest.Delete]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SumLens.Sum]=]  /home/be/CPP/algs_uerj/alg/list/tests/run-list-tests [==[--gtest_filter=SumLens.Sum]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SumLens.Sum]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SumLens.SumRec]=]  /home/be/CPP/algs_uerj/alg/list/tests/run-list-tests [==[--gtest_filter=SumLens.SumRec]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SumLens.SumRec]=]  PROPERTIES WORKING_DIRECTORY /home/be/CPP/algs_uerj/alg/list/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  run-list-tests_TESTS NoArraySingleLinkTest.InsertAndBasicStructure NoArraySingleLinkTest.Delete NoPointerSingleLinkTest.InsertAndBasicStructure NoPointerSingleLinkTest.Delete NoArrayDoubleLinkTest.InsertAndBasicStructure NoArrayDoubleLinkTest.Delete NoPointerDoubleLinkTest.InsertAndBasicStructure NoPointerDoubleLinkTest.Delete SumLens.Sum SumLens.SumRec)
